### ISSUE TITLE
Vagrant up failure

### ISSUE THREAD

**Issue by myttux10** [fgrehm/docker-provider#2]
Got the following error with `# vagrant up`. Vagrant version is 1.4.2

```
vagrant.d/gems/gems/docker-provider-0.0.2/lib/docker-provider/driver.rb:73:in `inspect': wrong number of arguments (0 for 1) (ArgumentError)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/plugin/v2/command.rb:192:in `inspect'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/plugin/v2/command.rb:192:in `block in with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/plugin/v2/command.rb:191:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/plugin/v2/command.rb:191:in `with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.2/plugins/commands/up/command.rb:56:in `block in execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/environment.rb:210:in `block (2 levels) in batch'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/environment.rb:208:in `tap'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/environment.rb:208:in `block in batch'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/environment.rb:207:in `synchronize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/environment.rb:207:in `batch'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.2/plugins/commands/up/command.rb:55:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/cli.rb:38:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/environment.rb:484:in `cli'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.2/bin/vagrant:127:in `<top (required)>'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
```

Vagrantfile:

```
 ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

# This is only needed if you are using the plugin from sources with bundler
Vagrant.require_plugin 'docker-provider'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 # This just fires up a container with a SSH server
  config.vm.define 'dummy' do |node|
    node.vm.box = 'dummy'
   # node.vm.box_url = 'http://bit.ly/vagrant-docker-dummy'

    node.vm.provider :docker do |docker|
      docker.image = 'fgrehm/vagrant-ubuntu:precise'
      docker.cmd   = ["/usr/sbin/sshd", "-D", "-e"]
    end
  end
end
```

**Comment by tylerwalts** [comment]
I am experiencing the same error, using the copy/paste Vagrantfile example from the readme, using Ubuntu 12.04 with Vagrant 1.4.3

**Comment by tonyseek** [comment]
+1

I am using Vagrant 1.4.3 with Arch Linux 3.12.7-2, and the Docker is 0.7.5.

**Comment by fgrehm** [comment]
This should be fixed on git, I'll push a new version to rubygems soonish
