### ISSUE TITLE
Error: create: No command specified

### ISSUE THREAD

**Issue by c10l** [fgrehm/docker-provider#8]
After creating a new docker image, Vagrant box and trying them out with a clean Vagrantfile, I get:

```
Bringing machine 'default' up with 'docker' provider...
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An unexpected error ocurred when executing the action on the
'default' machine. Please report this as a bug:

["docker", "run", "-name", "tmp_default_1393506132", "-d", "-v", "/private/tmp:/vagrant", "cassianoleal/vagrant-centos:6.5_nocm"]
2014/02/27 13:02:21 Error: create: No command specified


/Users/cassiano.leal/.vagrant.d/gems/gems/docker-provider-0.1.0/lib/docker-provider/driver.rb:114:in `execute'
/Users/cassiano.leal/.vagrant.d/gems/gems/docker-provider-0.1.0/lib/docker-provider/driver.rb:32:in `block in create'
```

More details (and the relevant files) on [this gist](https://gist.github.com/cassianoleal/9249636)

**Comment by c10l** [comment]
Ok, I fixed this by adding

```
CMD /usr/sbin/sshd -D -o UseDNS=no -o UsePAM=no
```

to the end of the `Dockerfile`. Maybe a bit of clarification on the documentation would suffice. :)

**Comment by fgrehm** [comment]
Yeah, I'm tagging this as a doc change and also as a bug since the provider should output a friendly error message :-)

**Comment by c10l** [comment]
:thumbsup:
